language: php

php:
  - 7.1
addons:
  chrome: beta

sudo: false

services:
  - mysql

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version
  - google-chrome --version
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - wget --no-check-certificate http://dev.drupal.no/sanitized.db

install:
  - cd $TRAVIS_BUILD_DIR
  - ./scripts/travis.sh

script:
  - composer test

