language: php
php:
  - 7.1

sudo: false

addons:
  chrome: stable

env:
  global:
    - DATABASE='drupal'
    - DB_USERNAME='root'
    - DB_ENCODE='utf8'

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

before_install:
  # Composer Configurations.
  # Make sure have latest composer
  - composer self-update --verbose
  - composer --version
  # Set php memory limit to -1 so composer update will not fail
  - export COMPOSER_MEMORY_LIMIT=-1
  # To enforce throwing an error and stopping package installation/update immediately
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1
  # Installing hirak/prestissimo allows composer to parallelise downloads which speeds up the composer install.
  - composer global require hirak/prestissimo

install:
  - composer install
  - touch web/sites/default/settings.local.php
  - ./vendor/bin/drush si minimal --db-url="mysql://$DB_USERNAME@127.0.0.1/$DATABASE" -y
  - ./vendor/bin/drush cset system.site uuid c431d00d-fe18-4aeb-9140-5e439ac2f365 -y
  - ./vendor/bin/drush cim -y
  - ./vendor/bin/drush updb -y
